SECTOR_MAP: dict[str, str] = {
    # NIFTY 50
    "ADANIENT": "Diversified",
    "ADANIPORTS": "Infrastructure",
    "APOLLOHOSP": "Healthcare",
    "ASIANPAINT": "Consumer",
    "AXISBANK": "Financials",
    "BAJAJ-AUTO": "Automobile",
    "BAJAJFINSV": "Financials",
    "BAJFINANCE": "Financials",
    "BEL": "Defence",
    "BHARTIARTL": "Telecom",
    "CIPLA": "Pharma",
    "COALINDIA": "Energy",
    "DRREDDY": "Pharma",
    "EICHERMOT": "Automobile",
    "ETERNAL": "Consumer",
    "GRASIM": "Cement",
    "HCLTECH": "IT",
    "HDFCBANK": "Financials",
    "HDFCLIFE": "Insurance",
    "HEROMOTOCO": "Automobile",
    "HINDALCO": "Metals",
    "HINDUNILVR": "FMCG",
    "ICICIBANK": "Financials",
    "INDUSINDBK": "Financials",
    "INFY": "IT",
    "ITC": "FMCG",
    "JIOFIN": "Financials",
    "JSWSTEEL": "Metals",
    "KOTAKBANK": "Financials",
    "LT": "Infrastructure",
    "M&M": "Automobile",
    "MARUTI": "Automobile",
    "MAXHEALTH": "Healthcare",
    "NESTLEIND": "FMCG",
    "NTPC": "Energy",
    "ONGC": "Energy",
    "POWERGRID": "Energy",
    "RELIANCE": "Energy",
    "SBILIFE": "Insurance",
    "SBIN": "Financials",
    "SHRIRAMFIN": "Financials",
    "SUNPHARMA": "Pharma",
    "TMPV": "Automobile",
    "TATACONSUM": "FMCG",
    "TATASTEEL": "Metals",
    "TCS": "IT",
    "TECHM": "IT",
    "TITAN": "Consumer",
    "TRENT": "Consumer",
    "ULTRACEMCO": "Cement",
    "WIPRO": "IT",
    # NIFTY NEXT 50
    "ABB": "Industrial",
    "ADANIENSOL": "Energy",
    "ADANIGREEN": "Energy",
    "ADANIPOWER": "Energy",
    "AMBUJACEM": "Cement",
    "BAJAJHFL": "Financials",
    "BAJAJHLDNG": "Financials",
    "BANKBARODA": "Financials",
    "BOSCHLTD": "Automobile",
    "BPCL": "Energy",
    "BRITANNIA": "FMCG",
    "CANBK": "Financials",
    "CGPOWER": "Industrial",
    "CHOLAFIN": "Financials",
    "DABUR": "FMCG",
    "DIVISLAB": "Pharma",
    "DLF": "Real Estate",
    "DMART": "Consumer",
    "GAIL": "Energy",
    "GODREJCP": "FMCG",
    "HAL": "Defence",
    "HAVELLS": "Industrial",
    "HYUNDAI": "Automobile",
    "ICICIGI": "Insurance",
    "ICICIPRULI": "Insurance",
    "INDHOTEL": "Hospitality",
    "INDIGO": "Aviation",
    "IOC": "Energy",
    "IRFC": "Financials",
    "JINDALSTEL": "Metals",
    "JSWENERGY": "Energy",
    "LICI": "Insurance",
    "LODHA": "Real Estate",
    "MOTHERSON": "Automobile",
    "NAUKRI": "IT",
    "PFC": "Financials",
    "PIDILITIND": "Industrial",
    "PNB": "Financials",
    "RECLTD": "Financials",
    "SHREECEM": "Cement",
    "SIEMENS": "Industrial",
    "SWIGGY": "Consumer",
    "TATAPOWER": "Energy",
    "TORNTPHARM": "Pharma",
    "TVSMOTOR": "Automobile",
    "UNITDSPR": "FMCG",
    "VBL": "FMCG",
    "VEDL": "Metals",
    "ZYDUSLIFE": "Pharma",
}

SECTOR_CATEGORIES: dict[str, list[str]] = {
    "Financials": ["AXISBANK", "HDFCBANK", "ICICIBANK", "KOTAKBANK", "SBIN", "INDUSINDBK", "BANKBARODA", "PNB", "CANBK", "BAJFINANCE", "BAJAJFINSV", "SHRIRAMFIN", "CHOLAFIN", "BAJAJHFL", "BAJAJHLDNG", "PFC", "RECLTD", "IRFC", "JIOFIN"],
    "IT": ["TCS", "INFY", "HCLTECH", "TECHM", "WIPRO", "NAUKRI"],
    "Pharma": ["SUNPHARMA", "CIPLA", "DRREDDY", "DIVISLAB", "TORNTPHARM", "ZYDUSLIFE"],
    "Automobile": ["MARUTI", "M&M", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO", "TVSMOTOR", "TMPV", "HYUNDAI", "MOTHERSON", "BOSCHLTD"],
    "Energy": ["RELIANCE", "ONGC", "BPCL", "IOC", "GAIL", "COALINDIA", "NTPC", "POWERGRID", "TATAPOWER", "JSWENERGY", "ADANIGREEN", "ADANIPOWER", "ADANIENSOL"],
    "Metals": ["TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDL", "JINDALSTEL"],
    "FMCG": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR", "GODREJCP", "TATACONSUM", "UNITDSPR", "VBL"],
    "Cement": ["ULTRACEMCO", "AMBUJACEM", "SHREECEM", "GRASIM"],
    "Consumer": ["TITAN", "TRENT", "ASIANPAINT", "DMART", "PIDILITIND", "ETERNAL", "SWIGGY"],
    "Insurance": ["HDFCLIFE", "SBILIFE", "ICICIGI", "ICICIPRULI", "LICI"],
    "Infrastructure": ["LT", "ADANIPORTS", "LODHA"],
    "Industrial": ["ABB", "SIEMENS", "HAVELLS", "CGPOWER"],
    "Healthcare": ["APOLLOHOSP", "MAXHEALTH"],
    "Defence": ["BEL", "HAL"],
    "Telecom": ["BHARTIARTL"],
    "Real Estate": ["DLF", "LODHA"],
    "Aviation": ["INDIGO"],
    "Hospitality": ["INDHOTEL"],
    "Diversified": ["ADANIENT"],
}

RELATED_SECTORS: dict[str, list[str]] = {
    "Financials": ["Insurance"],
    "Insurance": ["Financials"],
    "IT": [],
    "Pharma": ["Healthcare"],
    "Healthcare": ["Pharma"],
    "Automobile": ["Industrial"],
    "Industrial": ["Automobile", "Infrastructure"],
    "Infrastructure": ["Industrial", "Energy"],
    "Energy": ["Infrastructure"],
    "Metals": ["Industrial"],
    "FMCG": ["Consumer"],
    "Consumer": ["FMCG"],
    "Cement": ["Infrastructure", "Real Estate"],
    "Real Estate": ["Cement", "Infrastructure"],
    "Telecom": ["IT"],
    "Defence": ["Industrial"],
    "Aviation": ["Hospitality", "Industrial"],
    "Hospitality": ["Aviation", "Consumer"],
    "Diversified": [],
}


def get_sector(ticker: str) -> str | None:
    ticker_clean = ticker.upper().replace(".NS", "").strip()
    return SECTOR_MAP.get(ticker_clean)


def are_related_sectors(sector_a: str | None, sector_b: str | None) -> bool:
    if not sector_a or not sector_b:
        return False
    if sector_a == sector_b:
        return True
    return sector_b in RELATED_SECTORS.get(sector_a, [])
